services:
  postgres:
    image: postgres:16
    container_name: skillswap_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: skill_swap
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - skillswap_pgdata:/var/lib/postgresql/data

volumes:
  skillswap_pgdata: